# Generated by Django 5.2 on 2025-04-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='sequence_number',
            field=models.PositiveIntegerField(editable=False, help_text='Устанавливается автоматически при создании', null=True, unique=True, verbose_name='Номер товара'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category', verbose_name='Категория'),
        ),
    ]
