# Generated by Django 5.2 on 2025-04-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_sequence_number_alter_dish_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название акции')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Баннер акции')),
                ('is_active', models.BooleanField(default=True, help_text='Скрыть неактивные баннеры', verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше — тем раньше показывается', verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['order'],
            },
        ),
    ]
