# Generated by Django 5.2 on 2025-04-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_notificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=200, verbose_name='SMTP Host')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='SMTP Port')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('username', models.EmailField(max_length=254, verbose_name='SMTP Username')),
                ('password', models.CharField(max_length=200, verbose_name='SMTP Password')),
                ('default_from', models.EmailField(help_text='Будет использовано как DEFAULT_FROM_EMAIL', max_length=254, verbose_name='From address')),
            ],
            options={
                'verbose_name': 'SMTP-{{gender:settings}}',
                'verbose_name_plural': 'SMTP-{{gender:settings}}',
            },
        ),
    ]
